### ISSUE TITLE
Wrong header type in Makefile

### ISSUE THREAD

**Issue by nihilistaken** [HelifeWasTaken/VimTek#2]
**Describe the bug**
The wrong header appears when i use `<F3>` shortcut

**To Reproduce**

Can I reproduce the behavior ( Yes / No) Yes

Steps to reproduce the behavior: (Remove if you can't reproduce the behavior)
Use `<f3>` in a Makefile will result in the C header instead of the Makefile Header

**Expected behavior**
Makefile header appears

**Desktop (please complete the following information):**
 - OS: Fedora
 - Vim Version 9.0 Legacy (Redhat)

**Comment by HelifeWasTaken** [comment]
Hello, so this is not a bug:
```vim
map <F3> :set filetype=c<CR><bar>:<C-U>EpiHeader<CR>
map <F2> :<C-U>EpiHeader<CR>
```
Please use `<F2>` for the normal header `<F3>` is here only to force C Header in case of problem 😄
